(()=>{
  'use strict';
  const URLS={
    booking:'https://www.psalmistvibesstudio.com/schedule-a-free-consultation',
    website:'https://www.psalmistvibesstudio.com/',
    instagram:'https://www.instagram.com/psalmistvibesstudio/',
    maps:'https://www.google.com/maps/search/?api=1&query=3550+River+Run+Avenue+Nepean+Ottawa+K2J+3V5',
    phone:'tel:+16135014938'
  };
  const pages=[
    {name:'Invitation',asset:'event',parts:6,mime:'jpeg',ratio:'1170 / 1750',alt:'Find Your Sound — Psalmist Vibes Studio Fall 2026 event invitation',spots:[
      [30,51,50,9,'event','Open student performance information'],[25,69,57,9,'register','Open Fall 2026 registration'],[25,79,51,11,'book','Book a free introductory class'],
      [8,90,19,5,'meet','Meet Psalmist Vibes Studio'],[28,90,25,5,'book','Try an instrument'],[55,90,17,5,'challenge','Play the music challenge'],[73,90,21,5,'challenge','Play to win prizes'],
      [5,95,19,4,'phone','Call Psalmist Vibes Studio'],[24,95,28,4,'instagram','Open Instagram'],[52,95,31,4,'website','Open the official website'],[83,95,15,4,'maps','Open the studio location']
    ]},
    {name:'Free Intro',asset:'intro',parts:3,mime:'jpeg',ratio:'710 / 1536',alt:'Psalmist Vibes Studio free introductory class flyer',spots:[
      [19,40,65,23,'book','Book a free introductory class'],[50,62,34,14,'book','Use the QR destination'],
      [5,77,21,6,'meet','Meet Psalmist Vibes Studio'],[27,77,27,6,'book','Try an instrument'],[55,77,19,6,'challenge','Play the music challenge'],[74,77,23,6,'challenge','Play to win prizes']
    ]},
    {name:'Music Challenge',asset:'challenge',parts:3,mime:'jpeg',ratio:'1170 / 1516',alt:'Can You Beat the Music Challenge flyer',spots:[[4,18,92,77,'challenge','Wake up the poster and play the music challenge']]}
  ];
  const el=id=>document.getElementById(id),page=el('page'),frame=el('pageFrame'),previous=el('previous'),next=el('next'),dots=el('pageDots'),label=el('pageLabel'),veil=el('veil'),panel=el('paperPanel'),toast=el('toast'),soundToggle=el('soundToggle');
  let current=0,soundOn=true,audio=null,game=null,touchStart=null,toastTimer;
  const loadAsset=async p=>{const chunks=await Promise.all(Array.from({length:p.parts},(_,i)=>fetch(`assets/data/${p.asset}-${i+1}.txt`).then(r=>{if(!r.ok)throw Error('Missing artwork');return r.text()})));return `data:image/${p.mime};base64,${chunks.join('').replace(/\s/g,'')}`};
  const tone=(frequency=520,duration=.08,volume=.045)=>{if(!soundOn)return;audio=audio||new(window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type='sine';o.frequency.value=frequency;g.gain.setValueAtTime(volume,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+duration+.02)};
  function notify(message){toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
  function spark(x,y){const r=page.getBoundingClientRect();for(let i=0;i<7;i++){const s=document.createElement('i');s.className='spark';s.style.left=`${x-r.left}px`;s.style.top=`${y-r.top}px`;s.style.setProperty('--dx',`${(Math.random()-.5)*100}px`);s.style.setProperty('--dy',`${(Math.random()-.5)*100}px`);page.append(s);setTimeout(()=>s.remove(),800)}}
  function revealHotspots(){page.querySelectorAll('.hotspot').forEach((spot,i)=>setTimeout(()=>spot.classList.add('reveal'),i*75));setTimeout(()=>page.querySelectorAll('.hotspot').forEach(spot=>spot.classList.remove('reveal')),900)}
  function render(){const p=pages[current];frame.style.aspectRatio=p.ratio;page.replaceChildren();const img=new Image();img.alt=p.alt;img.src=p.src;img.draggable=false;page.append(img);p.spots.forEach(([x,y,w,h,action,aria],i)=>{const b=document.createElement('button');b.type='button';b.className='hotspot';b.setAttribute('aria-label',aria);Object.assign(b.style,{left:`${x}%`,top:`${y}%`,width:`${w}%`,height:`${h}%`});b.addEventListener('click',e=>{spark(e.clientX,e.clientY);tone(600+i*24);act(action)});page.append(b)});dots.replaceChildren(...pages.map((item,i)=>{const d=document.createElement('button');d.type='button';d.className=`dot${i===current?' active':''}`;d.setAttribute('aria-label',`Open ${item.name} page`);d.onclick=()=>go(i);return d}));label.textContent=`${p.name} · ${current+1} of ${pages.length}`;previous.disabled=current===0;next.disabled=current===pages.length-1;setTimeout(revealHotspots,450)}
  function go(index){if(index<0||index>=pages.length||index===current)return;const forward=index>current;frame.classList.add(forward?'turn-forward':'turn-back');tone(forward?610:480,.11);setTimeout(()=>{current=index;render()},190);setTimeout(()=>frame.classList.remove('turn-forward','turn-back'),480)}
  const head=title=>`<div class="panel-top"><div><p class="eyebrow">Psalmist Vibes Studio</p><h2 id="panelTitle">${title}</h2></div><button class="close" type="button" aria-label="Close">×</button></div>`;
  function open(html){panel.innerHTML=html;veil.hidden=false;document.body.style.overflow='hidden';panel.querySelector('.close').onclick=close;panel.querySelector('.close').focus()}
  function close(){veil.hidden=true;document.body.style.overflow='';panel.replaceChildren();game=null}
  function act(action){if(['book','register'].includes(action)){window.open(URLS.booking,'_blank','noopener');return}if(action==='phone'){location.href=URLS.phone;return}if(['instagram','website','maps'].includes(action)){window.open(URLS[action],'_blank','noopener');return}if(action==='challenge'){openChallenge();return}if(action==='meet')open(head('Come meet the studio')+`<p>Discover a warm music studio in Barrhaven for piano, voice and drums. Visit, call, or book the free introductory class directly.</p><div class="actions"><a class="action primary" href="${URLS.booking}" target="_blank" rel="noopener">Book a free introductory class</a><a class="action" href="${URLS.phone}">Call the studio</a><a class="action" href="${URLS.maps}" target="_blank" rel="noopener">Open location</a><a class="action" href="${URLS.instagram}" target="_blank" rel="noopener">Instagram</a><a class="action" href="${URLS.website}" target="_blank" rel="noopener">Official website</a></div>`);else if(action==='event')open(head('Find Your Sound')+`<p><strong>Student live performance: 1:30–2:00 PM.</strong></p><p>Support the students, meet the studio, try an instrument, play the music challenge and explore Fall 2026 registration—directly from the invitation.</p><div class="actions"><a class="action primary" href="${URLS.booking}" target="_blank" rel="noopener">Register / book a free intro</a><button class="action" type="button" data-play>Play the challenge</button><a class="action" href="${URLS.website}" target="_blank" rel="noopener">Official website</a></div>`);const play=panel.querySelector('[data-play]');if(play)play.onclick=()=>{close();go(2);setTimeout(openChallenge,500)}}
  function openChallenge(){open(head('Can You Beat the Music?')+`<p>The poster is awake. Listen to each pattern, then tap it back. Complete three rounds to reveal your reward.</p><div class="game-card"><div class="scoreboard"><span id="round">Round 1 / 3</span><span id="score">Score 0</span></div><div class="game-message" id="gameMessage">Press Start, then listen carefully.</div><div class="pads"><button class="pad" type="button" data-pad="0" aria-label="Drum">🥁</button><button class="pad" type="button" data-pad="1" aria-label="Clap">👏</button><button class="pad" type="button" data-pad="2" aria-label="Piano">🎹</button><button class="pad" type="button" data-pad="3" aria-label="Sparkle">✨</button></div><button class="game-start" id="gameStart" type="button">Start challenge</button><div class="prize" id="prize"><strong>You beat the music! 🎉</strong><span>Show this winning screen to Psalmist Vibes Studio at the event to ask about your prize.</span><a class="action primary" href="${URLS.booking}" target="_blank" rel="noopener">Book your free intro</a></div></div>`);game={round:1,score:0,sequence:[],input:[],locked:true};el('gameStart').onclick=beginRound;panel.querySelectorAll('.pad').forEach(b=>b.onclick=()=>press(+b.dataset.pad))}
  const frequencies=[170,260,392,540];
  function light(i){const b=panel.querySelector(`[data-pad="${i}"]`);if(!b)return;b.classList.add('lit');tone(frequencies[i],.18,.08);setTimeout(()=>b.classList.remove('lit'),250)}
  function beginRound(){game.sequence=Array.from({length:game.round+2},()=>Math.floor(Math.random()*4));game.input=[];game.locked=true;el('gameMessage').textContent='Listen…';el('gameStart').disabled=true;let i=0;const timer=setInterval(()=>{light(game.sequence[i++]);if(i===game.sequence.length){clearInterval(timer);setTimeout(()=>{if(!game)return;game.locked=false;el('gameMessage').textContent='Your turn — repeat the pattern.'},350)}},540)}
  function press(i){if(!game||game.locked)return;light(i);game.input.push(i);const at=game.input.length-1;if(i!==game.sequence[at]){game.locked=true;game.score=Math.max(0,game.score-5);el('score').textContent=`Score ${game.score}`;el('gameMessage').textContent='Almost! Listen again and retry this round.';el('gameStart').disabled=false;el('gameStart').textContent=`Retry round ${game.round}`;return}if(game.input.length===game.sequence.length){game.score+=game.round*25;el('score').textContent=`Score ${game.score}`;game.locked=true;if(game.round===3){el('gameMessage').textContent='Perfect finish!';el('gameStart').hidden=true;el('prize').classList.add('show');tone(880,.4,.08);return}game.round++;el('round').textContent=`Round ${game.round} / 3`;el('gameMessage').textContent='Nice! The next round is harder.';el('gameStart').disabled=false;el('gameStart').textContent=`Start round ${game.round}`}}
  previous.onclick=()=>go(current-1);next.onclick=()=>go(current+1);soundToggle.onclick=()=>{soundOn=!soundOn;soundToggle.textContent=soundOn?'♪':'♩';soundToggle.setAttribute('aria-pressed',String(soundOn));soundToggle.setAttribute('aria-label',soundOn?'Turn sound off':'Turn sound on');if(soundOn)tone(700)};veil.onclick=e=>{if(e.target===veil)close()};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!veil.hidden)close();if(veil.hidden&&e.key==='ArrowLeft')go(current-1);if(veil.hidden&&e.key==='ArrowRight')go(current+1)});frame.addEventListener('pointerdown',e=>touchStart={x:e.clientX,y:e.clientY});frame.addEventListener('pointerup',e=>{if(!touchStart)return;const dx=e.clientX-touchStart.x,dy=e.clientY-touchStart.y;touchStart=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25)go(current+(dx<0?1:-1))});
  page.innerHTML='<div style="height:100%;aspect-ratio:2/3;display:grid;place-items:center;padding:24px;background:#fffdfb;color:#3e3340;text-align:center;font-weight:800">Opening the magic book… ✨</div>';
  Promise.all(pages.map(loadAsset)).then(images=>{pages.forEach((p,i)=>p.src=images[i]);render();notify('The paper is alive — tap or swipe ✨')}).catch(error=>{console.error(error);page.innerHTML='<div style="height:100%;aspect-ratio:2/3;display:grid;place-items:center;padding:24px;background:#fffdfb;color:#3e3340;text-align:center">The magic book could not open. Please refresh.</div>'});
})();
